/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jasic_filip_chatapplication_Encryption */

#ifndef _Included_jasic_filip_chatapplication_Encryption
#define _Included_jasic_filip_chatapplication_Encryption
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jasic_filip_chatapplication_Encryption
 * Method:    encrypt
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jasic_filip_chatapplication_Encryption_encrypt
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     jasic_filip_chatapplication_Encryption
 * Method:    decrypt
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jasic_filip_chatapplication_Encryption_decrypt
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
